# Generated by Django 6.0 on 2026-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.JSONField(default=dict)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
